### ISSUE TITLE
It won't compile

### ISSUE THREAD

**Issue by catalincraciun** [brandonscott/nabu-ios#1]
The project won't compile, also there are some serious issues like importing NabuOpenSDK.h in both .m and .h files.

After some fixes, I get it to compile but still it doesn't work with my Nabu.

**Comment by brandonscott** [comment]
Can you provide some further debugging information? Make sure you're using the Utility app from the Developer Portal at: http://developer.razerzone.com

Do you have the SDK files downloaded and added to the project?

**Comment by catalincraciun** [comment]
Here is a screenshot, I have managed to compile it by adding your ViewController files and the method from the AppDelegate. The authentication works fine, but I can't get any interaction with my Nabu.

![screen shot 2015-03-15 at 12 20 36](https://cloud.githubusercontent.com/assets/5362999/6655612/bc738612-cb0d-11e4-8af6-c5e86598fcda.png)

**Comment by brandonscott** [comment]
This looks like the SDK you've imported is later version than the tutorial was built on, but I'm unsure that's why. Let me do some investigation and get back to you later.

**Comment by catalincraciun** [comment]
Ok, I am also trying to get it work, will let you know if I solve something. Let me send this test project I have build on email.

**Comment by brandonscott** [comment]
I won't be able to look until later this afternoon unfortunately. Your status codes are coming back as -1 and 0 which insinuates you're not authenticated properly. 

Also, just to confirm you're using the IOS Utility app found from the developer portal, not the App Store?

**Comment by catalincraciun** [comment]
I am using the iOS Utility app from the developer portal and also, the app shows on the "Connected Apps" section from the Utility.

**Comment by brandonscott** [comment]
Okay, I'll get back to you.

**Comment by catalincraciun** [comment]
NSURL *authUrl = [[NabuDataManager sharedDataManager] authorizationURLForAppID:@"test" andScope:@"fitness" withAppURISchemeCallback:@"BJCS"];

What's the app id here? Noticed it won't work with other app id.

**Comment by brandonscott** [comment]
That was my first thought actually.  The App ID's are generated by Razer and are API authentication tokens.  I replaced the token I generated for this with "test" so that it couldn't be abused.

Let me confirm tomorrow that it's okay to share the token with others, just so that it won't get blocked.

**Comment by catalincraciun** [comment]
Well, that means that's the problem... How to get my own API authentication tokens?

**Comment by brandonscott** [comment]
Yes, I know that's the problem, but I wanted to double check my code on my local machine first before replying back to you :)

The App ID's are provided per app, so I've already registered one for this app.  I just need to confirm that I have authorisation to share this token with you as obviously we want to control their use.

**Comment by catalincraciun** [comment]
Well, you don't need to share your credentials... I can register my own, but I don't really know how to do that.

**Comment by brandonscott** [comment]
Apps are registered here: http://developer.razerzone.com/nabu/developer-profile/

But as I said previously, the app already has it's own App ID.  I'll speak to someone tomorrow to ensure you can receive your own token to test out this app.

**Comment by catalincraciun** [comment]
I have my own testing app, I won't use yours, so I can register one by myself.

**Comment by brandonscott** [comment]
Okay, sure thing, hope this helped.

**Comment by catalincraciun** [comment]
I might need some help at registering my app. Still can't work it through. Submit app section needs an ipa.

**Comment by brandonscott** [comment]
Yes I know.  This is why I asked you if you would be able to wait until I've had time to speak with someone in the morning so that I can get a token provided to you for testing.

**Comment by catalincraciun** [comment]
Oh, sure thing. I will wait. This is my email: contact@catalincraciun.me

**Comment by brandonscott** [comment]
I will get in touch first thing, thanks for your patience.

**Comment by catalincraciun** [comment]
Got an AppID, the authentication returns this:

{
    Operation = 63;
    "Operation-Status" = 1;
    RequestID = "<NabuDataManager: 0x15d42730>";
}

Which looks good to me, but when checking the authentication it still returns 0:

{
    Operation = 53;
    "Operation-Status" = 0;
}

Can't understand why, do you have any guesses?

**Comment by catalincraciun** [comment]
Nevermind, I get it to work, you can close the issue. Thank you!
